### ISSUE TITLE
Ошибка при запуске yml with sip

### ISSUE THREAD

**Issue by sseroot** [basip/link#2]
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 128, column 65

**Comment by basipdev** [comment]
Added missing volumes 7ab745c00b41b10bf852714dfd9bd9519906b633

**Comment by sseroot** [comment]
Обновил, не помогло
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 128, column 65

**Comment by basipdev** [comment]
Провалидируйте ваш yml линтером - http://www.yamllint.com
Не можем повторить ошибку на своей стороне

**Comment by sseroot** [comment]
Сохранил страницу браузера. Ошибка в том же месте!
https://drive.google.com/file/d/1LwYmIqzVq9wrlQBjvlM7p9O_7XDp6TiX/view?usp=sharing

**Comment by basipdev** [comment]
https://user-images.githubusercontent.com/48123537/135844319-a6d42194-887b-4bc2-9461-158fd602bd0f.mov

**Comment by sseroot** [comment]
Установил. Но не открывается. Можно как-то подключиться дистанционно?

**Comment by basipdev** [comment]
Обращайтесь в поддержку.
